silentlyfailing/models.py
from datetime import datetime
from flask_login import UserMixin
import os
from slugify import slugify
from werkzeug.security import generate_password_hash, check_password_hash


from silentlyfailing import db


class User(UserMixin, db.Model):
    __tablename__ = 'user'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String)
    password = db.Column(db.String)
    authenticated = db.Column(db.Boolean, default=False)

    def set_password(self, password):
        self.password = generate_password_hash(password, method='sha256')

    def check_password(self, password):
        return check_password_hash(self.password, password)


class Post(db.Model):
    __tablename__ = 'post'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String)
    slug = db.Column(db.String(255))
    body = db.Column(db.String)
    created_date = db.Column(db.DateTime, nullable=False, default=datetime.now)
    last_updated = db.Column(db.DateTime, default=datetime.now)
    author = db.Column(db.String)

    def __repr__(self):
        return f'<Post {self.title}>'

    @property
    def serialize(self):
        return {
            'title': self.title,
            'body': self.body,
            'created_date': self.created_date,
            'last_updated': self.last_updated,
            'author': self.author,
        }

    @staticmethod
    def slugify(target, value, oldvalue, initiator):
        if value and (not target.slug or value != oldvalue):
            target.slug = slugify(value)

    def save(self):
        db.session.add(self)
        db.session.commit()

    def update(self, title, body):
        self.title = title
        self.body = body
        self.last_updated = datetime.now()
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()


def setup_admin_user(db):
    username = os.environ['ADMIN_USERNAME']
    password = os.environ['ADMIN_PASSWORD']
    user = User.query.filter_by(username=username).first()
    if not user:
        user = User(id=1, username=username)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()


db.event.listen(Post.title, 'set', Post.slugify, retval=False)

silentlyfailing/forms.py
from flask_wtf import FlaskForm
from flask_ckeditor import CKEditorField
from wtforms import StringField, PasswordField, SubmitField, validators
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    username = StringField('username', [validators.Length(min=4, max=25)])
    password = PasswordField('password', validators=[DataRequired()])
    submit = SubmitField('submit')


class PostForm(FlaskForm):
    title = StringField('title', [validators.Length(min=1, max=100)])
    body = CKEditorField('body', validators=[DataRequired()])
    author = StringField('author', [validators.Length(min=1, max=15)])
    submit = SubmitField('submit')

silentlyfailing/__init__.py
from distutils.core import setup
from flask import Flask
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask_ckeditor import CKEditor


db = SQLAlchemy()
migrate = Migrate()
ckeditor = CKEditor()
login_manager = LoginManager()
login_manager.login_view = "sf.login"


def create_app():
    app = Flask(__name__)

    if app.config["ENV"] == "production":
        app.config.from_object("config.ProductionConfig")
    else:
        app.config.from_object("config.DevelopmentConfig")

    # register blueprints
    from .routes import sf
    app.register_blueprint(sf)
    from .commands import setup_admin
    app.cli.add_command(setup_admin)

    with app.app_context():
        # initialize extensions
        db.init_app(app)
        migrate.init_app(app, db)
        login_manager.init_app(app)
        ckeditor.init_app(app)

    return app

silentlyfailing/routes.py
from flask import (
    Blueprint, flash, redirect, render_template, request, url_for
)
from flask_login import login_required, login_user, logout_user, current_user

from .models import User, Post
from .forms import LoginForm, PostForm
from silentlyfailing import login_manager


sf = Blueprint('sf', __name__)


@login_manager.user_loader
def load_user(user_id):
    try:
        return User.query.get(user_id)
    except:
        return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    flash('You must be logged in to view that page.')
    return redirect(url_for('sf.login'))


@sf.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('sf.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()

        if user and user.check_password(password=form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            return redirect(next_page or url_for('sf.index'))

        flash('Invalid username/password combination')

        return redirect(url_for('sf.login'))

    return render_template('login.html', form=form)


@sf.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('sf.index'))


@sf.route('/')
@sf.route("/index")
def index():
    posts = Post.query.all()
    return render_template('index.html', posts=posts)


@sf.route('/create-post', methods=['GET', 'POST'])
@login_required
def create_post():
    form = PostForm()

    if request.method == 'POST':
        if form.validate_on_submit():
            print(form)
            post = Post(title=form.title.data,
                        body=form.body.data.strip(),
                        author=form.author.data)
            post.save()
            return redirect(url_for('sf.index'))

    return render_template('create_post.html', form=form)


@sf.route('/<slug>/update-post', methods=('GET', 'POST'))
@login_required
def update_post(slug):
    post = get_post(slug)
    form = PostForm()

    if request.method == 'POST':
        if form.validate_on_submit():
            title = form.title.data
            body = form.body.data.strip()
            post.update(title, body)
            return redirect(url_for('sf.index'))

    return render_template('update_post.html', form=form, post=post)


@sf.route('/<slug>/delete-post', methods=('POST',))
@login_required
def delete_post(slug):
    post = get_post(slug)
    post.delete()
    return redirect(url_for('sf.index'))


@sf.route("/<slug>")
def post_detail(slug):
    post = get_post(slug)
    return render_template('post_detail.html', post=post)


def get_post(slug: str) -> Post:
    return Post.query.filter_by(slug=slug).first()

silentlyfailing/templates/_flash_errors.html
{% for message in get_flashed_messages() %}
<div class="alert alert-warning">
  <button type="button" class="close" data-dismiss="alert">
    x
  </button>
  {{ message }}
</div>
{% endfor %}

silentlyfailing/templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="{{ url_for('sf.index') }}">Silently Failing</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item"><a class="nav-link" href="#">About</a></li>
      </ul>
    </div>

    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
      <ul class="navbar-nav ms-auto">
        {% if current_user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" href="{{ url_for('sf.create_post') }}">Create Post</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('sf.logout') }}">Logout</a></li>
        {% else %}
        <li class="nav-item"><a class="nav-link" href="{{ url_for('sf.login') }}">Login</a></li>
        {% endif %}
      </ul>
    </div>

  </div>
</nav>

silentlyfailing/templates/_post_form.html
<div class=container"><br>
  <div class="row align-items-center justify-content-center">
    <div class="col-md-4">
      <form action='' method="post" role="form">
        {{ form.csrf_token }}
        <div class="form-group">

          <label for="title">Title:</label>
          {{ form.title(class='form-control', value=request.form['title'] or post.title) }}
          {% if form.title.errors %}
          <ul class="errors">
            {% for error in form.title.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
          {% endif %}

          <label for="body">Body:</label>
          {{ ckeditor.create(value=request.form['body'] or post.body, name='body') }}
          {{ ckeditor.load() }}
          {% if form.body.errors %}
          <ul class="errors">
            {% for error in form.body.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
          {% endif %}

          <label for="body">Author:</label>
          {{ form.author(class='form-control', value=request.form['author'] or post.author) }}
          {% if form.author.errors %}
          <ul class="errors">
            {% for error in form.author.errors %}
            <li>{{ error }}</li>{% endfor %}
          </ul>
          {% endif %}

          <center>
            {{ form.submit(class='btn btn-primary btn-lg mt-2') }}
          </center>


        </div>

      </form>

    </div>
  </div>
</div>

silentlyfailing/templates/_wtform_errors.html
{% for field, error in form.errors.items() %}
<div class="alert alert-error">{{field}} - {{" ".join(error)}}</div>
{% endfor %}

silentlyfailing/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="">

  <title>Silently Failing</title>

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  {% block extra_head %}
  {% endblock extra_head %}
</head>

<body>

  {% include "_navbar.html" %}

  <div class="container">
    {% if messages %}
    <div class="alert alert-danger">
      <strong>Error:</strong>
      <ul>
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}


    {% block content %}
    {% endblock %}
    {% block extra_body %}
    {% endblock extra_body %}
  </div>
</body>

</html>

silentlyfailing/templates/blog_form.html
<div class=container"><br>
  <div class="row align-items-center justify-content-center">
    <div class="col-md-4">
      <form action='' method="post" role="form">
        <div class="form-group">

          <label for="title">Title:</label>
          <input type="text" class="form-control" id="title" name="title" placeholder="Title"
            value="{{ request.form['title'] or post.title }}">
          </input>
          <br>

          <label for="body">Body:</label>
          <textarea class="form-control" id="body" name="body" placeholder="Article Contents"
            rows="10">{{ request.form['body'] or post.body }}</textarea>
          <br>

          <label for="email">Author:</label>
          <input type="text" class="form-control" id="author" name="author" placeholder="Author"
            value="{{ request.form['author'] or post.author }}">
          </input>

          <br>
        </div>

        <br>

        <center>
          <button type="submit" class="btn btn-primary btn-lg">
            Submit
          </button>
        </center>

      </form>

    </div>
  </div>
</div>

silentlyfailing/templates/create.html
{% extends 'base.html' %}

{% block extra_head %}
<div class="container"><br>
  <center>
    <h2>New Post</h2>
  </center>
</div>
{% endblock %}

{% block content %}

{% with post={} %}
{% include "blog_form.html" %}
{% endwith %}

{% endblock %}

silentlyfailing/templates/create_post.html
{% extends 'base.html' %}

{% block content %}

<div class="container"><br>
  <center>
    <h2>New Post</h2>
  </center>
</div>

{% with post={}, form=form %}
{% include "_post_form.html" %}
{% endwith %}

{% endblock %}

silentlyfailing/templates/detail.html
{% extends 'base.html' %}

{% block header %}
<h1>{% block title %}Posts{% endblock %}</h1>
{% if g.user %}
<a class="action" href="{{ url_for('sf.create') }}">New</a>
{% endif %}
{% endblock %}

{% block content %}
{% for post in posts %}
<article class="post">
  <header>
    <div>
      <h1>{{ post['title'] }}</h1>
      <div class="about">by {{ post['author'] }} on {{ post['created_date'].strftime('%Y-%m-%d') }}</div>
    </div>
    {% if current_user.is_authenticated %}
    <a class="action" href="{{ url_for('sf.update', id=post['id']) }}">Edit</a>
    {% endif %}
  </header>
  <p class="body">{{ post['body'] }}</p>
</article>
{% if not loop.last %}
<hr>
{% endif %}
{% endfor %}
{% endblock %}

silentlyfailing/templates/index.html
{% extends 'base.html' %}
{% block content %}
{% for post in posts %}
<div class="card mt-5">
  <div class="card-body">
    <h5 class="card-title">{{ post['title'] }}</h5>
    <p class="card-text">
    <p class="body">{{ post['body'] | safe | truncate(256, True)}}</p>
    </p>
    <p class="card-text">by {{ post['author'] }} on {{ post['created_date'].strftime('%Y-%m-%d') }}</p>
    <a href="{{ url_for('sf.post_detail', slug=post['slug']) }}" class="btn btn-primary">Read More</a>
    {% if current_user.is_authenticated %}

    <div class="btn-group mt-2">
      <form action="{{ url_for('sf.update_post', slug=post['slug']) }}" method="get">
        <input class="btn btn-primary btn-lg" type="submit" value="Edit">
      </form>
      <form action="{{ url_for('sf.delete_post', slug=post['slug']) }}" method="post">
        <input class="btn btn-danger btn-lg" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
      </form>
    </div>
    {% endif %}

  </div>
</div>
{% endfor %}

{% endblock %}

silentlyfailing/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="container">

  {% include "_flash_errors.html" %}

  <div class="row align-items-center justify-content-center">
    <div class="col-md-2 my-4 bg-light">
      <center>
        <h1 class="mt-2">Log In</h1>
      </center>
      <form method="POST" action="/login">
        {{ form.csrf_token }}
        <div class="form-group">

          {{ form.username(class='form-control my-2', placeholder='admin username') }}
          {% if form.username.errors %}
          <ul class="errors">
            {% for error in form.username.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
          {% endif %}

          {{ form.password(class='form-control my-2', placeholder='admin password') }}
          {% if form.password.errors %}
          <ul class="errors">
            {% for error in form.password.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
          {% endif %}

          <center>
            {{ form.submit(class='btn btn-primary btn-md my-2') }}
          </center>

        </div>
      </form>
    </div>
  </div>
  {% endblock %}
</div>

silentlyfailing/templates/post_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <table class="table table-hover">
    <tr>
      <td>
        <br>
        {{ post.body | safe }}
      </td>
    </tr>
  </table>
</div>
{% endblock %}

silentlyfailing/templates/update.html
{% extends 'create.html' %}
{% block extra_head %}
<div class="container"><br>
  <center>
    <h2>Edit "{{ post['title'] }}"</h2>
  </center>
</div>
{% endblock %}

{% block content %}
{% include "blog_form.html" %}

<center>
  <form action="{{ url_for('sf.delete', id=post['id']) }}" method="post">
    <input class="btn btn-danger btn-lg" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
  </form>
</center>

{% endblock %}

silentlyfailing/templates/update_post.html
{% extends 'base.html' %}

{% block content %}

<div class="container"><br>
  <center>
    <h2>Edit "{{ post['title'] }}"</h2>
  </center>
</div>

{% with form=form %}
{% include "_post_form.html" %}
{% endwith %}

<center>
  <form action="{{ url_for('sf.delete_post', slug=post['slug']) }}" method="post">
    <input class="btn btn-danger btn-lg" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
  </form>
</center>

{% endblock %}